esphome:
  name: transit-tracker
  friendly_name: Transit Tracker

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
  - source:
      type: local
      path: ../components

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    text_sensor: ERROR

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "ReplaceMe"
  password: "ReplaceMe!"
  power_save_mode: "NONE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TransitTracker Fallback Hotspot"
    password: "59541bEJiaf3"

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 192  # Initial brightness, from 0 to 255
    lambda: |-
      id(tracker).draw_schedule();

switch:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Power"
    restore_mode: ALWAYS_ON
    id: power

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    name: "Brightness"
    id: brightness

binary_sensor:
  # Increase brightness when up button is pressed
  - platform: gpio
    id: up_button
    pin:
      number: 6
      mode:
        input: true
        pullup: true
    filters:
      - settle: 100ms
    on_press:
      then:
        - lambda: |-
            auto br = id(brightness).state;
            if (id(power).state == false || br == 0.0) {
              // If off, turn back on
              id(power).turn_on();
              id(brightness).control(32);
            } else if (br >= 223.0) {
              id(brightness).control(255);
            } else {
              id(brightness).control(br + 32);
            }
  # Decrease brightness when down button is pressed
  - platform: gpio
    id: down_button
    pin:
      number: 7
      mode:
        input: true
        pullup: true
    filters:
      - settle: 100ms
    on_press:
      then:
        - lambda: |-
            auto br = id(brightness).state;
            if (br <= 32.0) {
              // Turn off
              id(power).turn_off();
            } else {
              id(brightness).control(br - 32);
            }

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - " "

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

color:
  - id: white
    hex: "A7A7A7"
  - id: blue
    hex: "273695"
  - id: silver
    hex: "B7B0B0"
  - id: crimson
    hex: "A60F2D"
  - id: cyan
    hex: "00A7A7"

transit_tracker:
  id: tracker
  base_url: "wss://pttracker.saucylegs.me/"
  limit: 6
  # Optional: Cycle through trips instead of showing them all at once
  max_trips_per_page: 3
  min_trips_per_page: 1
  page_cycle_duration: 5s
  feed_code: "pt"
  list_mode: nextPerRoute # Comment out this line to show all next trips, instead of just one for each route
  default_route_color: white
  show_vehicle_numbers: true
  stops:
    - stop_id: "9766759" # Flag Lane east bound
      routes:
        - "3139" # Apartmentland
        - "3135" # Blue
        - "5328" # Campus
        - "3138" # Loop
        - "3137" # Silver
        - "3545" # Wheat
        - "6848" # Airport direct
        - "6307" # Airport full
    - stop_id: "9767756" # Flag Lane west bound
      routes:
        - "3544" # Paradise
        - "3545" # Wheat
        - "3549" # Lentil
        - "6448" # From Airport direct
  styles:
    - route_id: "3135"
      name: "Blue"
      color: blue
    - route_id: "3137"
      name: "Silver"
      color: silver
    - route_id: "5328"
      name: "Campus"
      color: crimson
    - route_id: "6848"
      name: "To Airport"
      color: cyan
    - route_id: "6307"
      name: "To Airport"
      color: cyan
    - route_id: "6448"
      name: "From Airport"
      color: cyan
  abbreviations:
    - from: "Express"
      to: "Exp"
