esphome:
  name: transit-tracker
  friendly_name: Transit Tracker

esp32:
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: arduino

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
  - source:
      type: local
      path: ../components

logger:
  level: DEBUG
  logs:
    sensor: ERROR
    text_sensor: ERROR

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "ReplaceMe"
  password: "ReplaceMe!"
  power_save_mode: "NONE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TransitTracker Fallback Hotspot"
    password: "59541bEJiaf3"

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 255
    lambda: |-
      id(tracker).draw_schedule();

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - " "

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

color:
  - id: default
    hex: "A7A7A7"
  - id: blue
    hex: "273695"
  - id: silver
    hex: "B7B0B0"
  - id: crimson
    hex: "A60F2D"

transit_tracker:
  id: tracker
  base_url: "wss://pttracker.saucylegs.me/"
  limit: 3
  feed_code: "pt"
  default_route_color: default
  show_vehicle_numbers: true
  stops:
    - stop_id: "9766759" # Flag Lane east bound
      routes:
        - "3139" # Apartmentland
        - "3135" # Blue
        - "5328" # Campus
        - "3138" # Loop
        - "3137" # Silver
        - "3545" # Wheat
        - "6848" # Airport direct
        - "6307" # Airport full
    - stop_id: "9767756" # Flag Lane west bound
      routes:
        - "3544" # Paradise
        - "3545" # Wheat
        - "3549" # Lentil
        - "6448" # From Airport direct

  styles:
    - route_id: "3135"
      name: "Blue"
      color: blue
    - route_id: "3137"
      name: "Silver"
      color: silver
    - route_id: "5328"
      name: "Campus"
      color: crimson
  abbreviations:
    - from: "Express"
      to: "Exp"
    - from: "Airport - Departures (direct route)"
      to: "To Airport"
    - from: "Airport - Departures (full route)"
      to: "To Airport"
    - from: "From Airport - direct"
      to: "From Airport"